
image: billyboingo/docker-pipelines:node

pipelines:

  tags:
    v*:
      - step:
          caches:
            - node
          script:
            # Configure authentication for NPM
            - printf "//`node -p \"require('url').parse(process.env.NPM_REGISTRY_URL || 'https://registry.npmjs.org').host\"`/:_authToken=${NPM_TOKEN}\nregistry=${NPM_REGISTRY_URL:-https://registry.npmjs.org}\n" >> ~/.npmrc
            # Build
            - yarn
            - yarn build
            - npm publish --access public --tag next --unsafe-perm

  branches:
    dev:
      - step:
          caches:
            - node
          script:
            # Build
            - yarn
            - yarn clean
            - yarn test