
image: billyboingo/docker-pipelines:node

pipelines:

  branches:
    dev:
      - step:
          caches:
            - node
          script:
            - yarn
            - yarn test
            - npm version prerelease
            - npm publish --access public --tag next