
image: billyboingo/docker-pipelines:node

pipelines:

  custom:
    prerelease:
      - step:
          caches:
            - node
          script: 
            - git config user.email william@codification.org
            - git config user.name William Weiss
            - yarn
            - yarn test
            - npm version prerelease --unsafe-perm
            - npm publish --access public --tag next --unsafe-perm --registry=$NPM_REGISTRY_URL

  branches:
    dev:
      - step:
          caches:
            - node
          script:
            - yarn
            - yarn test