defaults: &defaults
  working_directory: ~/codification/commons-core
  parallelism: 1
  shell: /bin/bash --login

  environment:
    CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
    CIRCLE_TEST_REPORTS: /tmp/circleci-test-results

  docker:
    - image: circleci/node:8.11.1

version: 2

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Set Pacific Time Zone
          command: 'echo ''America/Los_Angeles'' | sudo tee -a /etc/timezone; sudo dpkg-reconfigure -f noninteractive tzdata;'
    - restore_cache:
        keys:
          - v1-dep-{{ .Branch }}-
          - v1-dep-master-
          - v1-dep-
      - run:
          name: Install dependencies
          command: yarn
      - save_cache:
          key: v1-dep-{{ .Branch }}-{{ epoch }}
          paths:
            - ./node_modules
      - run:
          name: Clean & Build
          command: yarn build
      - persist_to_workspace:
          root: ~/codification
          paths:
            - commons-core
          
workflows:
  version: 2
  just-build:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/